const fs = require('fs');
const path = require('path');

const vocabDir = path.join(__dirname, '..', 'src', 'data', 'vocab');

// Additional words for basic.json (~110 new words to bring it to 300)
const newBasicWords = [
    { word: "earn", partOfSpeech: "verb", meanings: ["to get by working", "to deserve"], exampleSentences: ["Earn money.", "Earn respect."] },
    { word: "effort", partOfSpeech: "noun", meanings: ["hard work", "attempt"], exampleSentences: ["Make an effort.", "Great effort shown."] },
    { word: "enable", partOfSpeech: "verb", meanings: ["to allow", "to make possible"], exampleSentences: ["Enable the feature.", "Education enables success."] },
    { word: "engage", partOfSpeech: "verb", meanings: ["to participate", "to attract"], exampleSentences: ["Engage the audience.", "Stay engaged."] },
    { word: "enjoy", partOfSpeech: "verb", meanings: ["to take pleasure in", "to like"], exampleSentences: ["Enjoy the music.", "She enjoys reading."] },
    { word: "ensure", partOfSpeech: "verb", meanings: ["to make sure", "to guarantee"], exampleSentences: ["Ensure safety.", "Ensure quality."] },
    { word: "enter", partOfSpeech: "verb", meanings: ["to go inside", "to input"], exampleSentences: ["Enter the room.", "Enter your name."] },
    { word: "establish", partOfSpeech: "verb", meanings: ["to set up", "to create"], exampleSentences: ["Establish rules.", "Establish a company."] },
    { word: "examine", partOfSpeech: "verb", meanings: ["to inspect", "to test"], exampleSentences: ["Examine the evidence.", "The doctor examined him."] },
    { word: "exchange", partOfSpeech: "verb", meanings: ["to swap", "to trade"], exampleSentences: ["Exchange ideas.", "Exchange gifts."] },
    { word: "exist", partOfSpeech: "verb", meanings: ["to be present", "to live"], exampleSentences: ["Does it exist?", "Problems exist."] },
    { word: "expect", partOfSpeech: "verb", meanings: ["to anticipate", "to hope"], exampleSentences: ["Expect the best.", "We expect results."] },
    { word: "explain", partOfSpeech: "verb", meanings: ["to make clear", "to describe"], exampleSentences: ["Explain the rule.", "Can you explain?"] },
    { word: "extend", partOfSpeech: "verb", meanings: ["to lengthen", "to expand"], exampleSentences: ["Extend the deadline.", "Extend your arm."] },
    { word: "fail", partOfSpeech: "verb", meanings: ["to not succeed", "to break down"], exampleSentences: ["Don't fail.", "The engine failed."] },
    { word: "feature", partOfSpeech: "noun", meanings: ["characteristic", "element"], exampleSentences: ["Key feature.", "New features."] },
    { word: "force", partOfSpeech: "verb", meanings: ["to make do", "to push"], exampleSentences: ["Force the door.", "Don't force it."] },
    { word: "forget", partOfSpeech: "verb", meanings: ["to not remember", "to leave behind"], exampleSentences: ["Don't forget.", "She forgot her keys."] },
    { word: "form", partOfSpeech: "verb", meanings: ["to create", "to shape"], exampleSentences: ["Form a team.", "Form an opinion."] },
    { word: "gain", partOfSpeech: "verb", meanings: ["to acquire", "to benefit"], exampleSentences: ["Gain experience.", "Gain weight."] },
    { word: "gather", partOfSpeech: "verb", meanings: ["to collect", "to assemble"], exampleSentences: ["Gather information.", "People gathered."] },
    { word: "give", partOfSpeech: "verb", meanings: ["to provide", "to donate"], exampleSentences: ["Give a gift.", "Give your opinion."] },
    { word: "goal", partOfSpeech: "noun", meanings: ["aim", "objective"], exampleSentences: ["Set a goal.", "Reach your goal."] },
    { word: "grow", partOfSpeech: "verb", meanings: ["to increase", "to develop"], exampleSentences: ["Grow a plant.", "The company grows."] },
    { word: "guess", partOfSpeech: "verb", meanings: ["to estimate", "to suppose"], exampleSentences: ["Guess the answer.", "I guess so."] },
    { word: "handle", partOfSpeech: "verb", meanings: ["to manage", "to deal with"], exampleSentences: ["Handle with care.", "She handled it well."] },
    { word: "happen", partOfSpeech: "verb", meanings: ["to occur", "to take place"], exampleSentences: ["What happened?", "It can happen."] },
    { word: "help", partOfSpeech: "verb", meanings: ["to assist", "to support"], exampleSentences: ["Help me please.", "He helped her."] },
    { word: "hope", partOfSpeech: "verb", meanings: ["to wish", "to expect"], exampleSentences: ["Hope for the best.", "I hope so."] },
    { word: "identify", partOfSpeech: "verb", meanings: ["to recognize", "to name"], exampleSentences: ["Identify the problem.", "Identify yourself."] },
    { word: "improve", partOfSpeech: "verb", meanings: ["to make better", "to enhance"], exampleSentences: ["Improve your skills.", "Things improved."] },
    { word: "include", partOfSpeech: "verb", meanings: ["to have as part", "to contain"], exampleSentences: ["Include everyone.", "Does it include tax?"] },
    { word: "increase", partOfSpeech: "verb", meanings: ["to grow", "to rise"], exampleSentences: ["Increase speed.", "Prices increased."] },
    { word: "inspire", partOfSpeech: "verb", meanings: ["to motivate", "to encourage"], exampleSentences: ["Inspire others.", "She inspired me."] },
    { word: "invite", partOfSpeech: "verb", meanings: ["to ask to come", "to welcome"], exampleSentences: ["Invite friends.", "Invited to dinner."] },
    { word: "judge", partOfSpeech: "verb", meanings: ["to evaluate", "to decide"], exampleSentences: ["Don't judge people.", "Judge the contest."] },
    { word: "keep", partOfSpeech: "verb", meanings: ["to retain", "to maintain"], exampleSentences: ["Keep a secret.", "Keep going."] },
    { word: "know", partOfSpeech: "verb", meanings: ["to be aware of", "to understand"], exampleSentences: ["Do you know?", "I know the answer."] },
    { word: "lack", partOfSpeech: "verb", meanings: ["to be without", "to need"], exampleSentences: ["Lack motivation.", "Lack of sleep."] },
    { word: "lead", partOfSpeech: "verb", meanings: ["to guide", "to be first"], exampleSentences: ["Lead the team.", "Lead the way."] },
    { word: "learn", partOfSpeech: "verb", meanings: ["to acquire knowledge", "to study"], exampleSentences: ["Learn a language.", "Learn from mistakes."] },
    { word: "leave", partOfSpeech: "verb", meanings: ["to depart", "to abandon"], exampleSentences: ["Leave now.", "Leave a message."] },
    { word: "let", partOfSpeech: "verb", meanings: ["to allow", "to permit"], exampleSentences: ["Let me try.", "Let it go."] },
    { word: "look", partOfSpeech: "verb", meanings: ["to see", "to search"], exampleSentences: ["Look carefully.", "Look for it."] },
    { word: "lose", partOfSpeech: "verb", meanings: ["to not find", "to fail to win"], exampleSentences: ["Lose the keys.", "Don't lose hope."] },
    { word: "love", partOfSpeech: "verb", meanings: ["to feel affection", "to enjoy deeply"], exampleSentences: ["Love your family.", "I love music."] },
    { word: "maintain", partOfSpeech: "verb", meanings: ["to keep up", "to preserve"], exampleSentences: ["Maintain order.", "Maintain your car."] },
    { word: "manage", partOfSpeech: "verb", meanings: ["to run", "to control"], exampleSentences: ["Manage a team.", "Manage your time."] },
    { word: "measure", partOfSpeech: "verb", meanings: ["to find size", "to assess"], exampleSentences: ["Measure the room.", "Measure progress."] },
    { word: "meet", partOfSpeech: "verb", meanings: ["to encounter", "to assemble"], exampleSentences: ["Meet a friend.", "Meet the deadline."] },
    { word: "mention", partOfSpeech: "verb", meanings: ["to refer to", "to say briefly"], exampleSentences: ["Mention your name.", "Don't mention it."] },
    { word: "miss", partOfSpeech: "verb", meanings: ["to fail to hit", "to feel absence"], exampleSentences: ["Miss the bus.", "I miss you."] },
    { word: "move", partOfSpeech: "verb", meanings: ["to change position", "to affect emotionally"], exampleSentences: ["Move to the city.", "The speech moved me."] },
    { word: "need", partOfSpeech: "verb", meanings: ["to require", "to want urgently"], exampleSentences: ["I need help.", "What do you need?"] },
    { word: "offer", partOfSpeech: "verb", meanings: ["to present", "to propose"], exampleSentences: ["Offer assistance.", "Offer a deal."] },
    { word: "open", partOfSpeech: "verb", meanings: ["to unlock", "to begin"], exampleSentences: ["Open the door.", "Open a new chapter."] },
    { word: "order", partOfSpeech: "verb", meanings: ["to command", "to request"], exampleSentences: ["Order food.", "Order a report."] },
    { word: "organize", partOfSpeech: "verb", meanings: ["to arrange", "to coordinate"], exampleSentences: ["Organize the files.", "Organize an event."] },
    { word: "overcome", partOfSpeech: "verb", meanings: ["to defeat", "to get past"], exampleSentences: ["Overcome fear.", "Overcome obstacles."] },
    { word: "participate", partOfSpeech: "verb", meanings: ["to take part", "to join"], exampleSentences: ["Participate in class.", "Everyone participated."] },
    { word: "perform", partOfSpeech: "verb", meanings: ["to carry out", "to act"], exampleSentences: ["Perform well.", "Perform a task."] },
    { word: "place", partOfSpeech: "verb", meanings: ["to put", "to set"], exampleSentences: ["Place it here.", "Place an order."] },
    { word: "plan", partOfSpeech: "verb", meanings: ["to intend", "to prepare"], exampleSentences: ["Plan a trip.", "Plan ahead."] },
    { word: "practice", partOfSpeech: "verb", meanings: ["to repeat to improve", "to carry out"], exampleSentences: ["Practice daily.", "Practice makes perfect."] },
    { word: "prepare", partOfSpeech: "verb", meanings: ["to make ready", "to plan"], exampleSentences: ["Prepare for the exam.", "Prepare a meal."] },
    { word: "present", partOfSpeech: "verb", meanings: ["to show", "to introduce"], exampleSentences: ["Present your work.", "Present a report."] },
    { word: "prevent", partOfSpeech: "verb", meanings: ["to stop", "to avoid"], exampleSentences: ["Prevent accidents.", "Prevent disease."] },
    { word: "produce", partOfSpeech: "verb", meanings: ["to make", "to create"], exampleSentences: ["Produce results.", "Produce goods."] },
    { word: "progress", partOfSpeech: "noun", meanings: ["advancement", "development"], exampleSentences: ["Make progress.", "Show progress."] },
    { word: "promote", partOfSpeech: "verb", meanings: ["to advance", "to advertise"], exampleSentences: ["Promote a product.", "Promoted to manager."] },
    { word: "protect", partOfSpeech: "verb", meanings: ["to keep safe", "to defend"], exampleSentences: ["Protect the environment.", "Protect yourself."] },
    { word: "prove", partOfSpeech: "verb", meanings: ["to demonstrate", "to show truth"], exampleSentences: ["Prove your point.", "Prove innocence."] },
    { word: "provide", partOfSpeech: "verb", meanings: ["to supply", "to give"], exampleSentences: ["Provide support.", "Provide food."] },
    { word: "reach", partOfSpeech: "verb", meanings: ["to arrive at", "to extend to"], exampleSentences: ["Reach the top.", "Reach your goal."] },
    { word: "read", partOfSpeech: "verb", meanings: ["to interpret text", "to understand"], exampleSentences: ["Read a book.", "Read between the lines."] },
    { word: "realize", partOfSpeech: "verb", meanings: ["to understand", "to achieve"], exampleSentences: ["Realize the truth.", "Realize a dream."] },
    { word: "receive", partOfSpeech: "verb", meanings: ["to get", "to accept"], exampleSentences: ["Receive a gift.", "Receive news."] },
    { word: "record", partOfSpeech: "verb", meanings: ["to document", "to register"], exampleSentences: ["Record the meeting.", "Set a record."] },
    { word: "reduce", partOfSpeech: "verb", meanings: ["to decrease", "to lower"], exampleSentences: ["Reduce waste.", "Reduce costs."] },
    { word: "refuse", partOfSpeech: "verb", meanings: ["to decline", "to reject"], exampleSentences: ["Refuse to give up.", "He refused the offer."] },
    { word: "remember", partOfSpeech: "verb", meanings: ["to recall", "to not forget"], exampleSentences: ["Remember the date.", "Try to remember."] },
    { word: "remove", partOfSpeech: "verb", meanings: ["to take away", "to eliminate"], exampleSentences: ["Remove the stain.", "Remove barriers."] },
    { word: "repeat", partOfSpeech: "verb", meanings: ["to do again", "to say again"], exampleSentences: ["Repeat after me.", "Don't repeat yourself."] },
    { word: "replace", partOfSpeech: "verb", meanings: ["to substitute", "to swap"], exampleSentences: ["Replace the battery.", "Replace old habits."] },
    { word: "require", partOfSpeech: "verb", meanings: ["to need", "to demand"], exampleSentences: ["Requires attention.", "This requires patience."] },
    { word: "resolve", partOfSpeech: "verb", meanings: ["to solve", "to decide firmly"], exampleSentences: ["Resolve a conflict.", "Resolve to improve."] },
    { word: "respect", partOfSpeech: "verb", meanings: ["to honor", "to admire"], exampleSentences: ["Respect others.", "Show respect."] },
    { word: "respond", partOfSpeech: "verb", meanings: ["to reply", "to react"], exampleSentences: ["Respond quickly.", "Respond to questions."] },
    { word: "result", partOfSpeech: "noun", meanings: ["outcome", "consequence"], exampleSentences: ["Good results.", "Results came in."] },
    { word: "return", partOfSpeech: "verb", meanings: ["to come back", "to give back"], exampleSentences: ["Return home.", "Return the book."] },
    { word: "risk", partOfSpeech: "noun", meanings: ["danger", "chance of loss"], exampleSentences: ["Take a risk.", "High risk."] },
    { word: "run", partOfSpeech: "verb", meanings: ["to move fast", "to operate"], exampleSentences: ["Run a marathon.", "Run a business."] },
    { word: "save", partOfSpeech: "verb", meanings: ["to keep safe", "to store"], exampleSentences: ["Save money.", "Save lives."] },
    { word: "seek", partOfSpeech: "verb", meanings: ["to look for", "to try to get"], exampleSentences: ["Seek advice.", "Seek the truth."] },
    { word: "send", partOfSpeech: "verb", meanings: ["to dispatch", "to transmit"], exampleSentences: ["Send an email.", "Send a package."] },
    { word: "share", partOfSpeech: "verb", meanings: ["to divide", "to give to others"], exampleSentences: ["Share knowledge.", "Share food."] },
    { word: "show", partOfSpeech: "verb", meanings: ["to display", "to demonstrate"], exampleSentences: ["Show your work.", "Show courage."] },
    { word: "solve", partOfSpeech: "verb", meanings: ["to find an answer", "to fix"], exampleSentences: ["Solve a problem.", "Solve the equation."] },
    { word: "spend", partOfSpeech: "verb", meanings: ["to use money", "to pass time"], exampleSentences: ["Spend wisely.", "Spend time with family."] },
    { word: "stay", partOfSpeech: "verb", meanings: ["to remain", "to not leave"], exampleSentences: ["Stay focused.", "Stay here."] },
    { word: "stop", partOfSpeech: "verb", meanings: ["to cease", "to halt"], exampleSentences: ["Stop talking.", "Stop the car."] },
    { word: "study", partOfSpeech: "verb", meanings: ["to learn", "to examine"], exampleSentences: ["Study hard.", "Study the results."] },
    { word: "suggest", partOfSpeech: "verb", meanings: ["to propose", "to recommend"], exampleSentences: ["Suggest an idea.", "She suggested a plan."] },
    { word: "support", partOfSpeech: "verb", meanings: ["to help", "to back up"], exampleSentences: ["Support a friend.", "Support the project."] },
    { word: "take", partOfSpeech: "verb", meanings: ["to carry", "to grab"], exampleSentences: ["Take a break.", "Take responsibility."] },
    { word: "talk", partOfSpeech: "verb", meanings: ["to speak", "to discuss"], exampleSentences: ["Talk to her.", "Talk business."] },
    { word: "teach", partOfSpeech: "verb", meanings: ["to instruct", "to educate"], exampleSentences: ["Teach a class.", "Teach others."] },
    { word: "think", partOfSpeech: "verb", meanings: ["to consider", "to believe"], exampleSentences: ["Think before acting.", "I think so."] },
    { word: "try", partOfSpeech: "verb", meanings: ["to attempt", "to test"], exampleSentences: ["Try your best.", "Try a new dish."] },
    { word: "turn", partOfSpeech: "verb", meanings: ["to rotate", "to change direction"], exampleSentences: ["Turn left.", "Turn the page."] },
    { word: "understand", partOfSpeech: "verb", meanings: ["to comprehend", "to know"], exampleSentences: ["Do you understand?", "Understand the rules."] },
    { word: "use", partOfSpeech: "verb", meanings: ["to employ", "to consume"], exampleSentences: ["Use a tool.", "Use common sense."] },
    { word: "visit", partOfSpeech: "verb", meanings: ["to go to see", "to call on"], exampleSentences: ["Visit a city.", "Visit a friend."] },
    { word: "wait", partOfSpeech: "verb", meanings: ["to stay", "to be patient"], exampleSentences: ["Wait here.", "Wait for results."] },
    { word: "win", partOfSpeech: "verb", meanings: ["to succeed", "to be victorious"], exampleSentences: ["Win a prize.", "Win the game."] },
    { word: "work", partOfSpeech: "verb", meanings: ["to do labor", "to function"], exampleSentences: ["Work hard.", "Does it work?"] },
    { word: "write", partOfSpeech: "verb", meanings: ["to compose", "to record"], exampleSentences: ["Write a letter.", "Write your name."] }
];

// Additional words for school.json (~100 new words)
const newSchoolWords = [
    { word: "argument", partOfSpeech: "noun", meanings: ["claim with evidence", "debate"], exampleSentences: ["Present your argument.", "Logical argument."] },
    { word: "assert", partOfSpeech: "verb", meanings: ["to state confidently", "to claim"], exampleSentences: ["Assert your rights.", "He asserted the truth."] },
    { word: "assignment", partOfSpeech: "noun", meanings: ["homework", "task given"], exampleSentences: ["Submit the assignment.", "Difficult assignment."] },
    { word: "brainstorm", partOfSpeech: "verb", meanings: ["to generate ideas", "to think creatively"], exampleSentences: ["Brainstorm solutions.", "Let's brainstorm."] },
    { word: "calculate", partOfSpeech: "verb", meanings: ["to compute", "to figure out"], exampleSentences: ["Calculate the total.", "Calculate the risk."] },
    { word: "challenge", partOfSpeech: "noun", meanings: ["difficult task", "obstacle"], exampleSentences: ["Accept the challenge.", "A big challenge."] },
    { word: "chapter", partOfSpeech: "noun", meanings: ["book section", "period"], exampleSentences: ["Read the chapter.", "A new chapter."] },
    { word: "collaborate", partOfSpeech: "verb", meanings: ["to work together", "to cooperate"], exampleSentences: ["Collaborate on projects.", "Teams collaborate."] },
    { word: "contribute", partOfSpeech: "verb", meanings: ["to give", "to add to"], exampleSentences: ["Contribute ideas.", "Contribute to society."] },
    { word: "curriculum", partOfSpeech: "noun", meanings: ["course of study", "syllabus"], exampleSentences: ["School curriculum.", "New curriculum."] },
    { word: "deadline", partOfSpeech: "noun", meanings: ["due date", "time limit"], exampleSentences: ["Meet the deadline.", "Strict deadline."] },
    { word: "debate", partOfSpeech: "noun", meanings: ["formal argument", "discussion"], exampleSentences: ["Hold a debate.", "Debate the topic."] },
    { word: "deduce", partOfSpeech: "verb", meanings: ["to conclude", "to reason"], exampleSentences: ["Deduce from clues.", "Deduce the answer."] },
    { word: "define", partOfSpeech: "verb", meanings: ["to explain meaning", "to specify"], exampleSentences: ["Define the term.", "Define your goals."] },
    { word: "demonstrate", partOfSpeech: "verb", meanings: ["to show", "to prove"], exampleSentences: ["Demonstrate the process.", "Demonstrate knowledge."] },
    { word: "derive", partOfSpeech: "verb", meanings: ["to obtain from", "to originate"], exampleSentences: ["Derive a formula.", "Derive meaning."] },
    { word: "determine", partOfSpeech: "verb", meanings: ["to find out", "to decide"], exampleSentences: ["Determine the cause.", "Determine a plan."] },
    { word: "diagnose", partOfSpeech: "verb", meanings: ["to identify", "to recognize"], exampleSentences: ["Diagnose a problem.", "Diagnose an illness."] },
    { word: "differentiate", partOfSpeech: "verb", meanings: ["to distinguish", "to tell apart"], exampleSentences: ["Differentiate between types.", "Differentiate clearly."] },
    { word: "discipline", partOfSpeech: "noun", meanings: ["control", "field of study"], exampleSentences: ["Need discipline.", "Scientific discipline."] },
    { word: "draft", partOfSpeech: "noun", meanings: ["rough version", "first attempt"], exampleSentences: ["Write a draft.", "First draft."] },
    { word: "elaborate", partOfSpeech: "verb", meanings: ["to explain in detail", "to add more"], exampleSentences: ["Elaborate your answer.", "Please elaborate."] },
    { word: "evaluate", partOfSpeech: "verb", meanings: ["to judge", "to assess"], exampleSentences: ["Evaluate results.", "Evaluate the essay."] },
    { word: "evidence", partOfSpeech: "noun", meanings: ["proof", "support"], exampleSentences: ["Gather evidence.", "Provide evidence."] },
    { word: "expand", partOfSpeech: "verb", meanings: ["to grow larger", "to develop further"], exampleSentences: ["Expand knowledge.", "Expand the essay."] },
    { word: "faculty", partOfSpeech: "noun", meanings: ["teaching staff", "ability"], exampleSentences: ["Meet the faculty.", "Faculty meeting."] },
    { word: "findings", partOfSpeech: "noun", meanings: ["results", "discoveries"], exampleSentences: ["Research findings.", "Discuss the findings."] },
    { word: "focus", partOfSpeech: "verb", meanings: ["to concentrate", "to center on"], exampleSentences: ["Focus on studies.", "Focus your attention."] },
    { word: "foundation", partOfSpeech: "noun", meanings: ["base", "fundamental principle"], exampleSentences: ["Strong foundation.", "Foundation of learning."] },
    { word: "framework", partOfSpeech: "noun", meanings: ["structure", "system"], exampleSentences: ["Theoretical framework.", "Build a framework."] },
    { word: "generate", partOfSpeech: "verb", meanings: ["to produce", "to create"], exampleSentences: ["Generate ideas.", "Generate income."] },
    { word: "grade", partOfSpeech: "noun", meanings: ["score", "level"], exampleSentences: ["Good grade.", "Grade the papers."] },
    { word: "highlight", partOfSpeech: "verb", meanings: ["to emphasize", "to mark"], exampleSentences: ["Highlight key points.", "Highlight in yellow."] },
    { word: "illustrate", partOfSpeech: "verb", meanings: ["to show with examples", "to draw"], exampleSentences: ["Illustrate your point.", "Illustrated textbook."] },
    { word: "implement", partOfSpeech: "verb", meanings: ["to carry out", "to put into action"], exampleSentences: ["Implement the plan.", "Implement changes."] },
    { word: "imply", partOfSpeech: "verb", meanings: ["to suggest", "to indicate"], exampleSentences: ["What does this imply?", "Imply without saying."] },
    { word: "infer", partOfSpeech: "verb", meanings: ["to draw conclusions", "to deduce"], exampleSentences: ["Infer the meaning.", "Infer from data."] },
    { word: "investigate", partOfSpeech: "verb", meanings: ["to research", "to examine"], exampleSentences: ["Investigate the topic.", "Police investigated."] },
    { word: "journal", partOfSpeech: "noun", meanings: ["diary", "academic publication"], exampleSentences: ["Keep a journal.", "Academic journal."] },
    { word: "justify", partOfSpeech: "verb", meanings: ["to give reasons for", "to prove"], exampleSentences: ["Justify your answer.", "Justify the decision."] },
    { word: "knowledge", partOfSpeech: "noun", meanings: ["understanding", "information"], exampleSentences: ["Build knowledge.", "Share knowledge."] },
    { word: "lecture", partOfSpeech: "noun", meanings: ["formal talk", "lesson"], exampleSentences: ["Attend a lecture.", "Guest lecture."] },
    { word: "literature", partOfSpeech: "noun", meanings: ["written works", "research papers"], exampleSentences: ["Review literature.", "Classic literature."] },
    { word: "logic", partOfSpeech: "noun", meanings: ["reasoning", "sense"], exampleSentences: ["Use logic.", "No logic."] },
    { word: "memorize", partOfSpeech: "verb", meanings: ["to learn by heart", "to commit to memory"], exampleSentences: ["Memorize the formula.", "Hard to memorize."] },
    { word: "method", partOfSpeech: "noun", meanings: ["procedure", "technique"], exampleSentences: ["Research method.", "Choose a method."] },
    { word: "motive", partOfSpeech: "noun", meanings: ["reason", "purpose"], exampleSentences: ["What is the motive?", "Understand motives."] },
    { word: "narrative", partOfSpeech: "noun", meanings: ["story", "account"], exampleSentences: ["Compelling narrative.", "Write a narrative."] },
    { word: "objective", partOfSpeech: "noun", meanings: ["goal", "aim"], exampleSentences: ["Clear objective.", "State the objective."] },
    { word: "observation", partOfSpeech: "noun", meanings: ["watching", "remark"], exampleSentences: ["Scientific observation.", "Make an observation."] },
    { word: "outline", partOfSpeech: "noun", meanings: ["summary plan", "structure"], exampleSentences: ["Write an outline.", "Outline the essay."] },
    { word: "paraphrase", partOfSpeech: "verb", meanings: ["to restate in own words", "to rephrase"], exampleSentences: ["Paraphrase the text.", "Please paraphrase."] },
    { word: "peer", partOfSpeech: "noun", meanings: ["equal", "classmate"], exampleSentences: ["Peer review.", "Learn from peers."] },
    { word: "perception", partOfSpeech: "noun", meanings: ["awareness", "understanding"], exampleSentences: ["Change perception.", "Good perception."] },
    { word: "prerequisite", partOfSpeech: "noun", meanings: ["required condition", "prior course"], exampleSentences: ["Check prerequisites.", "No prerequisites needed."] },
    { word: "primary", partOfSpeech: "adjective", meanings: ["main", "first"], exampleSentences: ["Primary source.", "Primary goal."] },
    { word: "principle", partOfSpeech: "noun", meanings: ["fundamental truth", "rule"], exampleSentences: ["Core principle.", "Guiding principles."] },
    { word: "process", partOfSpeech: "noun", meanings: ["series of steps", "procedure"], exampleSentences: ["Learning process.", "Follow the process."] },
    { word: "professor", partOfSpeech: "noun", meanings: ["university teacher", "expert"], exampleSentences: ["Ask the professor.", "Professor gave a lecture."] },
    { word: "proposal", partOfSpeech: "noun", meanings: ["suggestion", "plan"], exampleSentences: ["Research proposal.", "Submit proposal."] },
    { word: "prove", partOfSpeech: "verb", meanings: ["to demonstrate truth", "to show"], exampleSentences: ["Prove it.", "Prove the theorem."] },
    { word: "publish", partOfSpeech: "verb", meanings: ["to print and release", "to share publicly"], exampleSentences: ["Publish a paper.", "Published book."] },
    { word: "qualify", partOfSpeech: "verb", meanings: ["to meet standards", "to limit"], exampleSentences: ["Qualify for entry.", "Qualify the statement."] },
    { word: "question", partOfSpeech: "verb", meanings: ["to ask", "to doubt"], exampleSentences: ["Question assumptions.", "Never stop questioning."] },
    { word: "reflect", partOfSpeech: "verb", meanings: ["to think deeply", "to show"], exampleSentences: ["Reflect on learning.", "Reflect your thoughts."] },
    { word: "reinforce", partOfSpeech: "verb", meanings: ["to strengthen", "to support"], exampleSentences: ["Reinforce knowledge.", "Reinforce behavior."] },
    { word: "relevant", partOfSpeech: "adjective", meanings: ["related", "applicable"], exampleSentences: ["Relevant information.", "Stay relevant."] },
    { word: "research", partOfSpeech: "noun", meanings: ["investigation", "study"], exampleSentences: ["Conduct research.", "Research findings."] },
    { word: "review", partOfSpeech: "verb", meanings: ["to examine again", "to assess"], exampleSentences: ["Review notes.", "Peer review."] },
    { word: "revise", partOfSpeech: "verb", meanings: ["to edit", "to study again"], exampleSentences: ["Revise the essay.", "Revise for exams."] },
    { word: "scholarship", partOfSpeech: "noun", meanings: ["financial award", "academic study"], exampleSentences: ["Win a scholarship.", "Scholarship program."] },
    { word: "sequence", partOfSpeech: "noun", meanings: ["order", "series"], exampleSentences: ["In sequence.", "DNA sequence."] },
    { word: "significant", partOfSpeech: "adjective", meanings: ["important", "meaningful"], exampleSentences: ["Significant result.", "Significant impact."] },
    { word: "simulation", partOfSpeech: "noun", meanings: ["imitation", "model"], exampleSentences: ["Run a simulation.", "Computer simulation."] },
    { word: "solution", partOfSpeech: "noun", meanings: ["answer", "mixture"], exampleSentences: ["Find a solution.", "Chemical solution."] },
    { word: "source", partOfSpeech: "noun", meanings: ["origin", "reference"], exampleSentences: ["Cite the source.", "Reliable source."] },
    { word: "statement", partOfSpeech: "noun", meanings: ["declaration", "sentence"], exampleSentences: ["Thesis statement.", "Make a statement."] },
    { word: "strategy", partOfSpeech: "noun", meanings: ["plan", "approach"], exampleSentences: ["Study strategy.", "Good strategy."] },
    { word: "structure", partOfSpeech: "noun", meanings: ["organization", "framework"], exampleSentences: ["Essay structure.", "Clear structure."] },
    { word: "subject", partOfSpeech: "noun", meanings: ["topic", "school course"], exampleSentences: ["Favorite subject.", "Subject matter."] },
    { word: "summarize", partOfSpeech: "verb", meanings: ["to give main points", "to condense"], exampleSentences: ["Summarize the text.", "Please summarize."] },
    { word: "survey", partOfSpeech: "noun", meanings: ["questionnaire", "overview"], exampleSentences: ["Take a survey.", "Survey results."] },
    { word: "syllabus", partOfSpeech: "noun", meanings: ["course plan", "program of study"], exampleSentences: ["Check the syllabus.", "Course syllabus."] },
    { word: "synthesis", partOfSpeech: "noun", meanings: ["combination", "integration"], exampleSentences: ["Synthesis of ideas.", "Chemical synthesis."] },
    { word: "test", partOfSpeech: "noun", meanings: ["exam", "trial"], exampleSentences: ["Pass the test.", "Unit test."] },
    { word: "theory", partOfSpeech: "noun", meanings: ["explanation", "hypothesis"], exampleSentences: ["Scientific theory.", "Theory of evolution."] },
    { word: "title", partOfSpeech: "noun", meanings: ["name", "heading"], exampleSentences: ["Book title.", "Job title."] },
    { word: "topic", partOfSpeech: "noun", meanings: ["subject", "theme"], exampleSentences: ["Choose a topic.", "Main topic."] },
    { word: "translate", partOfSpeech: "verb", meanings: ["to convert language", "to explain"], exampleSentences: ["Translate the sentence.", "Translate ideas."] },
    { word: "understand", partOfSpeech: "verb", meanings: ["to comprehend", "to grasp"], exampleSentences: ["Understand the concept.", "Do you understand?"] },
    { word: "verify", partOfSpeech: "verb", meanings: ["to confirm", "to check"], exampleSentences: ["Verify the answer.", "Verify your identity."] }
];

// Additional words for travel.json (~100 new words)
const newTravelWords = [
    { word: "adventure", partOfSpeech: "noun", meanings: ["exciting experience", "journey"], exampleSentences: ["Great adventure.", "Adventure awaits."] },
    { word: "attraction", partOfSpeech: "noun", meanings: ["tourist site", "something appealing"], exampleSentences: ["Tourist attraction.", "Main attraction."] },
    { word: "backpack", partOfSpeech: "noun", meanings: ["travel bag", "rucksack"], exampleSentences: ["Pack a backpack.", "Backpack trip."] },
    { word: "border", partOfSpeech: "noun", meanings: ["country boundary", "edge"], exampleSentences: ["Cross the border.", "Border control."] },
    { word: "budget", partOfSpeech: "noun", meanings: ["financial plan", "limited money"], exampleSentences: ["Travel budget.", "Budget hotel."] },
    { word: "bus", partOfSpeech: "noun", meanings: ["public transport", "vehicle"], exampleSentences: ["Take the bus.", "Bus schedule."] },
    { word: "campsite", partOfSpeech: "noun", meanings: ["camping area", "outdoor stay"], exampleSentences: ["Find a campsite.", "Nice campsite."] },
    { word: "captain", partOfSpeech: "noun", meanings: ["ship commander", "leader"], exampleSentences: ["Ship captain.", "The captain spoke."] },
    { word: "carry-on", partOfSpeech: "noun", meanings: ["cabin bag", "hand luggage"], exampleSentences: ["Check carry-on size.", "Carry-on bag."] },
    { word: "charter", partOfSpeech: "noun", meanings: ["private hire", "rental"], exampleSentences: ["Charter a flight.", "Charter a boat."] },
    { word: "climate", partOfSpeech: "noun", meanings: ["weather pattern", "environment"], exampleSentences: ["Warm climate.", "Study the climate."] },
    { word: "coast", partOfSpeech: "noun", meanings: ["shoreline", "seaside"], exampleSentences: ["Beautiful coast.", "Coastal town."] },
    { word: "compass", partOfSpeech: "noun", meanings: ["direction tool", "navigational device"], exampleSentences: ["Use a compass.", "Lost without compass."] },
    { word: "confirm", partOfSpeech: "verb", meanings: ["to verify", "to finalize"], exampleSentences: ["Confirm booking.", "Confirm your seat."] },
    { word: "connecting", partOfSpeech: "adjective", meanings: ["linking", "joining"], exampleSentences: ["Connecting flight.", "Connecting rooms."] },
    { word: "continent", partOfSpeech: "noun", meanings: ["large landmass", "major region"], exampleSentences: ["African continent.", "Visit a continent."] },
    { word: "convenience", partOfSpeech: "noun", meanings: ["ease", "accessibility"], exampleSentences: ["For your convenience.", "Travel convenience."] },
    { word: "countryside", partOfSpeech: "noun", meanings: ["rural area", "landscape"], exampleSentences: ["Beautiful countryside.", "Drive through countryside."] },
    { word: "currency", partOfSpeech: "noun", meanings: ["money", "local cash"], exampleSentences: ["Exchange currency.", "Local currency."] },
    { word: "depart", partOfSpeech: "verb", meanings: ["to leave", "to set off"], exampleSentences: ["Depart at noon.", "When do we depart?"] },
    { word: "directions", partOfSpeech: "noun", meanings: ["instructions for route", "guidance"], exampleSentences: ["Ask for directions.", "Follow the directions."] },
    { word: "domestic", partOfSpeech: "adjective", meanings: ["within a country", "local"], exampleSentences: ["Domestic flight.", "Domestic tourism."] },
    { word: "drive", partOfSpeech: "verb", meanings: ["to operate a vehicle", "to travel by car"], exampleSentences: ["Drive to the airport.", "Long drive."] },
    { word: "dusk", partOfSpeech: "noun", meanings: ["twilight", "evening time"], exampleSentences: ["Beautiful dusk.", "At dusk."] },
    { word: "embassy", partOfSpeech: "noun", meanings: ["diplomatic office", "government building"], exampleSentences: ["Visit the embassy.", "Contact the embassy."] },
    { word: "embark", partOfSpeech: "verb", meanings: ["to board", "to begin journey"], exampleSentences: ["Embark on adventure.", "Embark the ship."] },
    { word: "estimate", partOfSpeech: "verb", meanings: ["to approximate", "to calculate roughly"], exampleSentences: ["Estimate travel time.", "Rough estimate."] },
    { word: "excursion", partOfSpeech: "noun", meanings: ["day trip", "short journey"], exampleSentences: ["Book an excursion.", "Day excursion."] },
    { word: "expedition", partOfSpeech: "noun", meanings: ["organized journey", "exploration"], exampleSentences: ["Mountain expedition.", "Scientific expedition."] },
    { word: "fare", partOfSpeech: "noun", meanings: ["ticket price", "cost of travel"], exampleSentences: ["Bus fare.", "Affordable fare."] },
    { word: "festival", partOfSpeech: "noun", meanings: ["celebration", "cultural event"], exampleSentences: ["Music festival.", "Local festival."] },
    { word: "ferry", partOfSpeech: "noun", meanings: ["water transport", "boat"], exampleSentences: ["Take the ferry.", "Ferry crossing."] },
    { word: "foreign", partOfSpeech: "adjective", meanings: ["from another country", "unfamiliar"], exampleSentences: ["Foreign language.", "Foreign country."] },
    { word: "gallery", partOfSpeech: "noun", meanings: ["art museum", "exhibition space"], exampleSentences: ["Visit the gallery.", "Art gallery."] },
    { word: "GPS", partOfSpeech: "noun", meanings: ["navigation system", "location tracker"], exampleSentences: ["Use GPS.", "GPS coordinates."] },
    { word: "guide", partOfSpeech: "noun", meanings: ["tour leader", "instruction book"], exampleSentences: ["Hire a guide.", "Travel guide."] },
    { word: "harbor", partOfSpeech: "noun", meanings: ["port", "shelter for ships"], exampleSentences: ["Enter the harbor.", "Harbor view."] },
    { word: "heritage", partOfSpeech: "noun", meanings: ["cultural tradition", "history"], exampleSentences: ["Cultural heritage.", "Heritage site."] },
    { word: "hiking", partOfSpeech: "noun", meanings: ["walking in nature", "trekking"], exampleSentences: ["Go hiking.", "Hiking trail."] },
    { word: "hostel", partOfSpeech: "noun", meanings: ["budget accommodation", "shared lodging"], exampleSentences: ["Stay at hostel.", "Youth hostel."] },
    { word: "insurance", partOfSpeech: "noun", meanings: ["protection plan", "coverage"], exampleSentences: ["Travel insurance.", "Buy insurance."] },
    { word: "international", partOfSpeech: "adjective", meanings: ["between countries", "global"], exampleSentences: ["International flight.", "International travel."] },
    { word: "island", partOfSpeech: "noun", meanings: ["land surrounded by water", "remote place"], exampleSentences: ["Tropical island.", "Small island."] },
    { word: "jetlag", partOfSpeech: "noun", meanings: ["time zone fatigue", "travel exhaustion"], exampleSentences: ["Severe jetlag.", "Manage jetlag."] },
    { word: "jungle", partOfSpeech: "noun", meanings: ["tropical forest", "dense vegetation"], exampleSentences: ["Explore the jungle.", "Jungle trek."] },
    { word: "local", partOfSpeech: "adjective", meanings: ["from the area", "nearby"], exampleSentences: ["Local food.", "Ask a local."] },
    { word: "map", partOfSpeech: "noun", meanings: ["diagram of area", "guide"], exampleSentences: ["Read a map.", "City map."] },
    { word: "metro", partOfSpeech: "noun", meanings: ["subway", "underground train"], exampleSentences: ["Take the metro.", "Metro station."] },
    { word: "monument", partOfSpeech: "noun", meanings: ["memorial structure", "landmark"], exampleSentences: ["Historical monument.", "Visit monument."] },
    { word: "museum", partOfSpeech: "noun", meanings: ["collection display", "cultural institution"], exampleSentences: ["Natural history museum.", "Visit the museum."] },
    { word: "nationality", partOfSpeech: "noun", meanings: ["country of origin", "citizenship"], exampleSentences: ["State nationality.", "What is your nationality?"] },
    { word: "navigate", partOfSpeech: "verb", meanings: ["to find way", "to steer"], exampleSentences: ["Navigate the city.", "Navigate by stars."] },
    { word: "overnight", partOfSpeech: "adjective", meanings: ["all night", "the next morning"], exampleSentences: ["Overnight stay.", "Overnight train."] },
    { word: "peninsula", partOfSpeech: "noun", meanings: ["land with water on three sides", "promontory"], exampleSentences: ["Beautiful peninsula.", "Korean peninsula."] },
    { word: "permit", partOfSpeech: "noun", meanings: ["official permission", "license"], exampleSentences: ["Work permit.", "Entry permit."] },
    { word: "picturesque", partOfSpeech: "adjective", meanings: ["beautiful", "scenic"], exampleSentences: ["Picturesque village.", "Picturesque view."] },
    { word: "port", partOfSpeech: "noun", meanings: ["harbor", "dock"], exampleSentences: ["Cruise port.", "Port city."] },
    { word: "resort", partOfSpeech: "noun", meanings: ["vacation place", "holiday complex"], exampleSentences: ["Beach resort.", "Ski resort."] },
    { word: "roundtrip", partOfSpeech: "noun", meanings: ["there and back ticket", "return journey"], exampleSentences: ["Roundtrip ticket.", "Book roundtrip."] },
    { word: "safari", partOfSpeech: "noun", meanings: ["wildlife expedition", "nature tour"], exampleSentences: ["African safari.", "Safari jeep."] },
    { word: "scenic", partOfSpeech: "adjective", meanings: ["beautiful view", "picturesque"], exampleSentences: ["Scenic route.", "Scenic viewpoint."] },
    { word: "seaside", partOfSpeech: "noun", meanings: ["near the sea", "coastal"], exampleSentences: ["Seaside town.", "Seaside holiday."] },
    { word: "sightseeing", partOfSpeech: "noun", meanings: ["visiting attractions", "tourism"], exampleSentences: ["Go sightseeing.", "Sightseeing tour."] },
    { word: "souvenir", partOfSpeech: "noun", meanings: ["memento", "keepsake"], exampleSentences: ["Buy a souvenir.", "Souvenir shop."] },
    { word: "taxi", partOfSpeech: "noun", meanings: ["hired car", "cab"], exampleSentences: ["Hail a taxi.", "Taxi to hotel."] },
    { word: "temple", partOfSpeech: "noun", meanings: ["religious building", "place of worship"], exampleSentences: ["Ancient temple.", "Buddhist temple."] },
    { word: "timezone", partOfSpeech: "noun", meanings: ["regional time zone", "clock zone"], exampleSentences: ["Different timezone.", "Adjust to timezone."] },
    { word: "toll", partOfSpeech: "noun", meanings: ["road fee", "charge"], exampleSentences: ["Pay the toll.", "Toll booth."] },
    { word: "tourist", partOfSpeech: "noun", meanings: ["visitor", "traveler"], exampleSentences: ["Many tourists.", "Tourist spot."] },
    { word: "trail", partOfSpeech: "noun", meanings: ["path", "track"], exampleSentences: ["Hiking trail.", "Follow the trail."] },
    { word: "train", partOfSpeech: "noun", meanings: ["railway vehicle", "series"], exampleSentences: ["Board the train.", "Train station."] },
    { word: "transit", partOfSpeech: "noun", meanings: ["passing through", "transport"], exampleSentences: ["In transit.", "Transit visa."] },
    { word: "trek", partOfSpeech: "noun", meanings: ["long journey", "hike"], exampleSentences: ["Mountain trek.", "Long trek."] },
    { word: "tropical", partOfSpeech: "adjective", meanings: ["hot and humid", "near equator"], exampleSentences: ["Tropical island.", "Tropical climate."] },
    { word: "tunnel", partOfSpeech: "noun", meanings: ["underground passage", "highway tube"], exampleSentences: ["Drive through tunnel.", "Mountain tunnel."] },
    { word: "urban", partOfSpeech: "adjective", meanings: ["city related", "metropolitan"], exampleSentences: ["Urban tourism.", "Urban landscape."] },
    { word: "waterfall", partOfSpeech: "noun", meanings: ["falling water", "cascade"], exampleSentences: ["Beautiful waterfall.", "Waterfall hike."] },
    { word: "wilderness", partOfSpeech: "noun", meanings: ["wild nature", "uninhabited land"], exampleSentences: ["Explore wilderness.", "Wild wilderness."] },
    { word: "wildlife", partOfSpeech: "noun", meanings: ["wild animals", "nature"], exampleSentences: ["See wildlife.", "Wildlife reserve."] },
    { word: "yacht", partOfSpeech: "noun", meanings: ["luxury boat", "sailing vessel"], exampleSentences: ["Rent a yacht.", "Yacht cruise."] }
];

function expandFile(filename, newWords) {
    const filePath = path.join(vocabDir, filename);
    const existing = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    const existingLower = new Set(existing.map(w => w.word.toLowerCase()));

    let added = 0;
    for (const w of newWords) {
        if (!existingLower.has(w.word.toLowerCase())) {
            existing.push(w);
            existingLower.add(w.word.toLowerCase());
            added++;
        }
    }

    fs.writeFileSync(filePath, JSON.stringify(existing, null, 4), 'utf8');
    console.log(`${filename}: was ${existing.length - added}, added ${added} → now ${existing.length}`);
}

expandFile('basic.json', newBasicWords);
expandFile('school.json', newSchoolWords);
expandFile('travel.json', newTravelWords);

// Total count
const total = ['basic.json', 'school.json', 'travel.json'].reduce((sum, f) => {
    return sum + JSON.parse(fs.readFileSync(path.join(vocabDir, f), 'utf8')).length;
}, 0);
console.log(`\nTotal across all files: ${total} words`);

// Duplicate check
console.log('\nChecking for cross-file duplicates...');
const allWords = new Map();
let dupes = 0;
for (const f of ['basic.json', 'school.json', 'travel.json']) {
    const data = JSON.parse(fs.readFileSync(path.join(vocabDir, f), 'utf8'));
    for (const item of data) {
        const w = item.word.toLowerCase();
        if (allWords.has(w)) {
            console.log(`  DUPE: "${w}" in ${f} + ${allWords.get(w)}`);
            dupes++;
        } else {
            allWords.set(w, f);
        }
    }
}
console.log(dupes === 0 ? 'No duplicates found!' : `${dupes} duplicate(s) found.`);
